### ISSUE TITLE
During port-forwarding, StreamDemuxer returns extra bytes at the beginning

### ISSUE THREAD

**Issue by xinyanmsft** [kubernetes-client/csharp#229] opened 2019-01-22 17:36 UTC
Environment: Azure Kubernetes Service, version 1.11.5
To repro:
1. Start a port-forwarding StreamDemuxer to a pod in K8s, with "v4.channel.k8s.io". 
2. var stream = streamDemuxer.GetStream(0, null)
3. call stream.Read 

Result:
the first 2 bytes received from the above stream is the port number, not the bytes transmitted from server.

**Comment by itowlson** [comment] 2019-01-22 21:16
@xinyanmsft The title of the issue says 'sometimes' - does your repro exhibit the behaviour consistently, or is it intermittent?  If intermittent, about how often do you see it?

cc @brendandburns

**Comment by xinyanmsft** [comment] 2019-01-22 21:19
with my setup (AKS 1.11.5) I am seeing this behavior consistently in my cluster. Updated the title to remove the word 'sometimes'

**Comment by brendandburns** [comment] 2019-01-24 00:06
Yep, this is the port-forward protocol. We should read those bytes.  I'll look at fixing.

**Comment by brendandburns** [comment] 2019-01-27 06:31
I wrote an example in #232, I can't seem to reproduce this (though I know for a fact that's part of the streaming protocol....)

Do you have the code for a repro?

Thanks

**Comment by xinyanmsft** [comment] 2019-01-28 22:34
Looked into this issue, created PR https://github.com/kubernetes-client/csharp/pull/233

The root cause of this bug is in StreamDemuxer.cs. It does not have code to filter out the port bytes in all cases. However, the bug will only manifest itself if one calls StreamDemuxer.GetStream before calling StreamDemuxer.Start. If StreamDemuxer.Start is called first, everything will appear to work because the port bytes are discarded upon receiving due to no listener.

**Comment by brendandburns** [comment] 2019-02-05 04:01
Closing since #233 has merged.

**Closed by brendandburns** 2019-02-05 04:01 UTC
Labels: kind/bug
