### ISSUE TITLE
Watch() missing events after a while

### ISSUE THREAD

**Issue by ahoka** [kubernetes-client/csharp#515] opened 2020-11-02 13:14 UTC
We are using Watch to wait for pod completion, but in some cases we miss the completion event.

var pods = client.ListNamespacedPodWithHttpMessagesAsync(config.Namespace, watch: true, fieldSelector: $"metadata.name={pod}");
pods.Watch<V1Pod, V1PodList>((type, item) =>..., ..., ...);

We don't see OnClose or OnError firing when this happens. The first few events are arriving correctly.

Could this be that the underlying connection breaks for some reason, but the stream does not notice it?

**Comment by tg123** [comment] 2020-11-03 16:28
so `completion event` is something like when pod was finished?

here are all events from server side

https://github.com/kubernetes-client/csharp/blob/16845bae1d8dda30407b3bdb375a9b5800eca12c/src/KubernetesClient/Watcher.cs#L12

 * Added
 * Modified
 * Deleted
 * Bookmark
 * Error

maybe, you can push some user event to a queue

**Comment by CarlosLanderas** [comment] 2020-11-21 02:07
I found the problem. This is a regression from the previous version. Probably you can see in the logs:

[02:06:50 ERR] The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.

or some kind of timeout or taskcancelledexception. I am adding the watch reconnection on error

**Comment by eskaufel** [comment] 2020-12-15 13:55
duplicate of #533 ?

**Comment by brendandburns** [comment] 2020-12-19 16:31
Yes, I think so. I'm going to close it in favor of that issue where there's much more discussion.

**Closed by brendandburns** 2020-12-19 16:31 UTC
