### ISSUE TITLE
Unable to patch deployment container ports via existing V1Deployment 

### ISSUE THREAD

**Issue by kuldeepGDI** [kubernetes-client/csharp#527] opened 2020-11-23 17:01 UTC
Hi, I am successfully able  to do a patch on deployment via  [json](https://github.com/kubernetes-client/csharp/blob/master/examples/patch/Program.cs) string as mentioned in samples. However, i noticed that when multiple containers are present then merge Patch is removing the container that i am not changing.

Therefore as an alternative approach my idea is to
1) get the deployment (V1Deployment)
2) Update the V1Deployment based on LINQ where clause and update container ports for a container in V1Deployment
3) Patch the V1Deployment object I have received in step 1. 

I am unable to figure out a way to just how can i achieve step 3. I looked at [this](https://github.com/kubernetes-client/csharp/issues/78#issuecomment-372048262)  but I get following error while i try to do it.

`{
	"kind": "Status",
	"apiVersion": "v1",
	"metadata": {},
	"status": "Failure",
	"message": " \"\" is invalid: patch: Invalid value: \"[]\": couldn't get version/kind; json parse error: json: cannot unmarshal array into Go value of type struct { APIVersion string \"json:\\\"apiVersion,omitempty\\\"\"; Kind string \"json:\\\"kind,omitempty\\\"\" }",
	"reason": "Invalid",
	"details": {
		"causes": [{
			"reason": "FieldValueInvalid",
			"message": "Invalid value: \"[]\": couldn't get version/kind; json parse error: json: cannot unmarshal array into Go value of type struct { APIVersion string \"json:\\\"apiVersion,omitempty\\\"\"; Kind string \"json:\\\"kind,omitempty\\\"\" }",
			"field": "patch"
		}]
	},
	"code": 422
}`

My code

![image](https://user-images.githubusercontent.com/61690328/99992555-c78aeb00-2db6-11eb-8f53-26285951178e.png)

I am pretty sure my code is wrong at the moment, but i am just not getting how can i pass back the updated V1Deployment object to k8s via patch call. I think this way the updated object should get updated, please correct me if i am wrong ? 

Thank you

**Update**

I am now able to do it via ReplaceDeployment method. I just update the ports and Replace the entire deployment object with updated one. However, I am not sure if this is the best/only approach for what I am trying to achieve ? Please suggest

**Comment by tg123** [comment] 2020-11-25 13:31
you are sending json patch, but type is merge patch

**Comment by brendandburns** [comment] 2020-11-25 16:15
Replace is fine. Especially when you are reading, updating, then writing. Using the 'replace' methods is actually preferable.

As you note, the semantics of patch can be tricky to get right, replace is easier.

Patch is usually useful when there is a single small change (e.g. add a label) that doesn't require you to read the object ahead of time.

**Comment by brendandburns** [comment] 2020-11-25 16:15
I'm going to close this as I think the issue is answered. Feel free to `/reopen` if you need further assistance.

**Closed by brendandburns** 2020-11-25 16:15 UTC

**Comment by kuldeepGDI** [comment] 2020-11-25 16:34
great thanks a lot for your inputs !
