### ISSUE TITLE
What is the possible cause of "Connection reset by peer" when watching ListNamespacedPodWithHttpMessagesAsync

### ISSUE THREAD

**Issue by AntonPetrov83** [kubernetes-client/csharp#773] opened 2022-02-04 04:51 UTC
Hi!

A have an AKS (Azure Kubernetes Service) and recently when I deployed my app I started receiving an exception:
```
System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer.
 ---> System.Net.Sockets.SocketException (104): Connection reset by peer
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.FillAsync(Boolean async)
   at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.ReadAsyncCore(Memory`1 buffer, CancellationToken cancellationToken)
   at k8s.WatcherDelegatingHandler.CancelableStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.IO.StreamReader.ReadBufferAsync(CancellationToken cancellationToken)
   at System.IO.StreamReader.ReadLineAsyncInternal()
   at k8s.Watcher`1.WatcherLoop(CancellationToken cancellationToken)

   ...
```

Later it stopped responding like that. Is it a transient error? Or should I investigate?

P.S. My app is based on Microsoft.Orleans and there is a `Orleans.Hosting.Kubernetes` extension which uses `ListNamespacedPodWithHttpMessagesAsync` API.

**Comment by tg123** [comment] 2022-02-04 05:30
see #533
this could be mitigated by add tcp keepalive or using http2 which was included in 6.x+

**Comment by AntonPetrov83** [comment] 2022-02-04 05:44
The strange thing is it's the first time I encounter such exceptions and we work like that half a year already. And another strange thing is it stopped throwing exceptions after some time. If you look into the [code](https://github.com/dotnet/orleans/blob/dd6aabae71cfba657c7ecf277ee40ab71e9c74b0/src/Orleans.Hosting.Kubernetes/KubernetesClusterAgent.cs#L268) you will see Orleans handles exception in a loop so I guess now it stabilized and works ax expected...

**Comment by tg123** [comment] 2022-02-04 06:09
`Connection reset by peer`  might be caused by any routing node to the dst endpoint.
it is a underlayer network issue.

in the case #533, we noticed that it caused by LB kicked idle connections. retrying maybe the solution if it is caused by network layer.

**Comment by zhiweiv** [comment] 2022-02-07 02:34
> see #533 this could be mitigated by add tcp keepalive or using http2 which was included in 6.x+
@tg123 
For client 7.x on .net 6.0, can you add more details about http2? Can it send tcp keep alive automatically without  os level change?
The workaround in https://github.com/kubernetes-client/csharp/issues/533#issuecomment-749418238 is too complex.

**Comment by tg123** [comment] 2022-02-07 12:51
> > see #533 this could be mitigated by add tcp keepalive or using http2 which was included in 6.x+
> 
> @tg123 For client 7.x on .net 6.0, can you add more details about **http2**? Can it send tcp keep alive automatically without os level change? The workaround in [#533 (comment)](https://github.com/kubernetes-client/csharp/issues/533#issuecomment-749418238) is too complex.

http2 is default if your server supports it (https).
but you have to set os level keepalive if does not

**Comment by zhiweiv** [comment] 2022-02-08 06:25
I found the workaround https://github.com/kubernetes-client/csharp/issues/533#issuecomment-749418238 has been merged, and there is property KubernetesClientConfiguration.TcpKeepAlive to control it, but it only works for .net 5, I added PR https://github.com/kubernetes-client/csharp/pull/777 to support .net 6, please take a look.

**Comment by zhiweiv** [comment] 2022-02-08 09:04
The is no good way to change tcp keepalive in container level, seems it is Linux kernel level setting, see https://stackoverflow.com/questions/69302681/setting-tcp-keepalive-on-a-container. 

I have to keep the application level monitor logic, reset watch after N minutes no new data.  I have to do this because I am running workload in AKS with basic load balancer. BLB will silently drop the connection for idle connection(SLB will sent RST to client and server, aka the Connection reset by peer), the watch will hang forever.

**Comment by zhiweiv** [comment] 2022-02-08 09:12
I am wondering does SocketsHttpHandler.KeepAlivePingDelay in http2 can send keepalive correctly without the kernel setting change. It doesn't mention in https://docs.microsoft.com/en-us/dotnet/api/system.net.http.socketshttphandler.keepalivepingdelay?view=net-6.0.

**Comment by zhiweiv** [comment] 2022-02-09 01:03
Is it ok to update code in https://github.com/kubernetes-client/csharp/blob/master/src/KubernetesClient/Kubernetes.ConfigInit.cs#L195 to following now? 
This enable http2 keepalive when KubernetesClientConfiguration.TcpKeepAlive is true. I can test if it work in my aks cluster after get merged.
```
var sh = new SocketsHttpHandler
{
    KeepAlivePingPolicy = HttpKeepAlivePingPolicy.WithActiveRequests,
    KeepAlivePingDelay = new TimeSpan(0, 3, 0),
    KeepAlivePingTimeout = new TimeSpan(0, 0, 30)  
};
```

**Comment by tg123** [comment] 2022-02-09 02:00
@zhiweiv thanks 
we forget to merge #590 lets do it

cc @brendanburns

**Comment by zhiweiv** [comment] 2022-02-09 02:14
For the KeepAlivePingDelay, the 3mins is a bit long, the idle time of AKS basic load balancer is 4mins, I am afraid it is not enough in that case. Can you recommend the value of KeepAlivePingDelay?

**Comment by tg123** [comment] 2022-02-11 17:52
> For the KeepAlivePingDelay, the 3mins is a bit long, the idle time of AKS basic load balancer is 4mins, I am afraid it is not enough in that case. Can you recommend the value of KeepAlivePingDelay?

let test 3 mins first.

**Comment by zhiweiv** [comment] 2022-02-14 02:25
PR submitted, please take a look.

**Comment by zhiweiv** [comment] 2022-02-17 11:00
The 7.0.13 fixed **Connection reset by peer** in my test, @AntonPetrov83  you can take a try. The .net version should be 5.0+.

**Comment by tg123** [comment] 2022-02-17 11:45
> The 7.0.13 fixed **Connection reset by peer** in my test, @AntonPetrov83 you can take a try. The .net version should be 5.0+.

Thanks for PR and verification

**Closed by tg123** 2022-02-17 11:45 UTC
