### ISSUE TITLE
Windows 11 HTTP/2 handshake error

### ISSUE THREAD

**Issue by anongitmous** [kubernetes-client/csharp#746] opened 2021-11-19 00:39 UTC
Hello,
I have a project that was built and working on Windows 10 using Visual Studio 2019 and .NET 5.0 for many months. As part of an attempt to get GPU support in WSL, I updated this machine to Windows 11. After the upgrade, my KubernetesCllient project would no longer work: any time I tried to run a command against the same remote k8s cluster I had been running against for many months on Windows 10, I would get an HTTP/2 handshake exception. To eliminate any extraneous libraries and frameworks that I was using in my project from the experiments, I created a tiny Visual Studio 2019 project using the same version of KubernetesClient that my project was using: 5.0.17.  It failed with the same error. I also installed Visual Studio 2022 and built a tiny project in that using KubernetesClient 6.0.25 (along with .NET 6.0) and it failed with the same error. I then brought up a new VM running Windows 10 updated all the way through 21H2 released just recently, and both the console app built with .NET 5.0 using KubernetesClient v5.0.17 using Visual Studio 2019 as well as the console app built with .NET 6.0 using KubernetesClient 6.0.25 worked without problem. I then created a brand new, vanilla Windows 11 VM, and both of those console apps failed with the exact same error about HTTP/2 handshake. So, this has been validated to work on two different Windows 10 installations, and to fail on two Windows 11 installations. It seems to be pointing to an issue with the KubernetesClient on Windows 11.

The two sample projects (very simple, single source file project which exercises only pod retrieval and imports only KubernetesClient via NuGet):

Project using Visual Studio 2019 with .NET 5.0 and KubernetesClient 5.0.17
https://github.com/anongitmous/SampleKubeApp

Project using Visual Studio 2022 with .NET 6.0 and KubernetesClient 6.0.25
https://github.com/anongitmous/SampleKubeAppVS2022

These two projects each create a console app and both

**Work Fine on Windows 10 Versions-**
Windows 10 (my previous version before the update to Win 11)
Windows 10 21H2 OS Build 19044.1379

**Throw HTTP/2 Handshake exception on Windows 11-**
Windows 11 21H2 OS Build 22000.346
Windows 11 21H2 OS Build 22000.194

To run either console app, simply supply the kube config file and the context you wish to use, e.g.:
`.\SampleKubeApp.exe kubeconfig somecontext`

The full exception stack I get when running either of the sample apps in Windows 11:
```
Unhandled exception. System.Net.Http.HttpRequestException: An HTTP/2 connection could not be established because the server did not complete the HTTP/2 handshake.
   at System.Net.Http.HttpConnectionPool.ReturnHttp2Connection(Http2Connection connection, Boolean isNewConnection)
   at System.Net.Http.HttpConnectionPool.AddHttp2ConnectionAsync(HttpRequestMessage request)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetResult(TResult result)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
   at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetResult(TResult result)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.SetResult()
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
   at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetResult(TResult result)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
   at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetResult(TResult result)
   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|187_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Threading.ThreadPool.<>c.<.cctor>b__87_0(Object state)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.InvokeContinuation(Action`1 continuation, Object state, Boolean forceAsync, Boolean requiresExecutionContextFlow)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs _)
   at System.Net.Sockets.SocketAsyncEventArgs.OnCompletedInternal()
   at System.Net.Sockets.SocketAsyncEventArgs.<>c.<.cctor>b__179_0(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading.ThreadPoolBoundHandleOverlapped.CompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pNativeOverlapped)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at k8s.Kubernetes.ListPodForAllNamespacesWithHttpMessagesAsync(Nullable`1 allowWatchBookmarks, String continueParameter, String fieldSelector, String labelSelector, Nullable`1 limit, Nullable`1 pretty, String resourceVersion, String resourceVersionMatch, Nullable`1 timeoutSeconds, Nullable`1 watch, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Program.<<Main>$>g__GetItems|0_0(String kubeCfg, String kubeCtx) in C:\Data\Development\C#\SampleKubeAppVS2022\SampleKubeAppVS2022\Program.cs:line 20
   at Program.<Main>$(String[] args) in C:\Data\Development\C#\SampleKubeAppVS2022\SampleKubeAppVS2022\Program.cs:line 3
   at Program.<Main>(String[] args)

```

Thanks in advance for reading through the above and for any help.

**Comment by tg123** [comment] 2021-11-19 01:52
Thanks for the detail
any info about the server side?

I upgraded to Windows 11 on day1, seems I did not notice it

**Comment by anongitmous** [comment] 2021-11-19 02:01
Anything in particular? This is the version info returned from `kubectl version`:

> Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

Thanks.

**Comment by tg123** [comment] 2021-11-19 14:21
not sure if it is related to your cluster version. it is too old.
I tested with 1.21 on 10.0.22000.318, did not repro your err

can you test a direct httpclient get to your api server?

**Comment by anongitmous** [comment] 2021-11-19 15:18
> not sure if it is related to your cluster version. it is too old. I tested with 1.21 on 10.0.22000.318, did not repro your err
> 
> can you test a direct httpclient get to your api server?

Not sure how I would do that, but willing to try. Are there instructions somewhere?

Also, happily, I just this week got a new cluster to run commands against and it's running 1.21+, and my stuff works again (your question about the server version prompted me to try my sample programs against it). So it appears that this is an issue of something changing in Windows 11 that makes the KubernetesClient unable to complete the handshake with older kube clusters?

Thanks.

**Comment by brendandburns** [comment] 2021-11-19 21:24
Is it just WebSockets/HTTP/2 connections that fail? Or is it any HTTP request?

My bet would be that this is TLS related.

Easiest way to try it would be to just use `curl` or `Invoke-WebRequest` in PowerShell.

Don't worry about the auth, my guess is that the connection will drop before you even get there.

**Comment by tg123** [comment] 2021-11-19 23:11
you can also check tls by open you api server url (must be https) via browser
![image](https://user-images.githubusercontent.com/170430/142702288-efcb55d4-f3e1-4987-b768-8d71d0f1fd90.png)
to check the tls version


may caused by 1.13 cluster was using an unsupported tls version by windows11

**Comment by brendandburns** [comment] 2021-11-22 16:59
I'm going to close this because I don't think it is a client issue.

Please use `/reopen` if you believe that it is caused by this client.

**Closed by brendandburns** 2021-11-22 16:59 UTC
