### ISSUE TITLE
Getting "Unathorized" response when kubectl is working? 

### ISSUE THREAD

**Issue by amsoedal** [kubernetes-client/csharp#624] opened 2021-05-18 18:53 UTC
Hi, we have a customer who's been reporting that our CLI returns "unathorized" when they try to interact with their cluster, but when they use other kubernetes tools (kubectl, or the node kubernetes client) that everything works fine. Since our CLI relies on the c# kubernetes client, is there a possible issue related to this? They say they doesn't have access to the default namespace, but we're trying to list pods in a specified (non-default) namespace on their behalf.

**Comment by tg123** [comment] 2021-05-18 19:53
`var config = KubernetesClientConfiguration.BuildDefaultConfig();` to have same config loading pattern as kubectl

**Comment by brendandburns** [comment] 2021-05-18 23:36
It's always possible that we don't support some authentication method. Can you paste the details of the kubeconfig file (with secrets redacted, obviously)

**Comment by jarrett-confrey** [comment] 2021-05-19 00:18
@brendanburns i am the one whos seeing the issue, this is what my kubeeconfig looks like
```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ...
    server: ...
  name: ...
contexts:
- context:
    cluster: ...
    namespace: ...
    user: ...
  name: ...
current-context: ...
kind: Config
preferences: {}
users:
- name: ...
  user:
    auth-provider:
      config:
        client-id: gangway
        client-secret: ...
        id-token: ...
        idp-issuer-url: https://dex...
        refresh-token: ...
      name: oidc
```

**Comment by brendandburns** [comment] 2021-05-19 14:28
The OIDC provider is here:

https://github.com/kubernetes-client/csharp/blob/master/src/KubernetesClient/Authentication/OidcTokenProvider.cs

and loaded here:

https://github.com/kubernetes-client/csharp/blob/2cbad3d42926d58729e9bb537de2200d746b9d90/src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs#L412

I don't see anything that jumps out as being wrong, but I suspect that there is some sort of problem with the intersection of the client and your OIDC provider.

**Comment by brendandburns** [comment] 2021-05-19 14:29
Note that OIDC support was only added in January 2021, so if you are using an old version of the client library that may be the cause.

**Comment by amsoedal** [comment] 2021-05-19 14:37
@brendandburns that definitely sounds possible. I'll need to double check.

**Comment by amsoedal** [comment] 2021-05-19 17:48
I checked with my team, and apparently the last time we updated was explicitly so that we could pull in the OIDC support (we're on version 4.0.16).

**Comment by jarrett-confrey** [comment] 2021-05-19 18:02
how can i help debug the potential issue with my oidc provider? the javascript kubernetes client does not have this issue so it seems possible to fix

**Comment by brendandburns** [comment] 2021-05-19 18:22
If you could try cloning this repo and running one (or more) of the [examples](https://github.com/kubernetes-client/csharp/tree/master/examples) and report back whether that works (or if an exception is thrown) that would definitely help.

You should be able to just `dotnet run` in any one of the examples directory.

Otherwise, a visual inspection of the differences between the [javascript oidc](https://github.com/kubernetes-client/javascript/blob/master/src/oidc_auth.ts) and the csharp implementation might be useful.

Thanks!

**Comment by jarrett-confrey** [comment] 2021-05-19 21:14
heres the exception that im seeing. i dont know csharp but i can attempt to compare implementation later
```
Starting Request!
Unhandled exception. Microsoft.Rest.HttpOperationException: Operation returned an invalid status code 'Unauthorized'
   at k8s.Kubernetes.ListNamespacedPodWithHttpMessagesAsync(String namespaceParameter, Nullable`1 allowWatchBookmarks, String continueParameter, String fieldSelector, String labelSelector, Nullable`1 limit, String resourceVersion, String resourceVersionMatch, Nullable`1 timeoutSeconds, Nullable`1 watch, String pretty, Dictionary`2 customHeaders, CancellationToken cancellationToken) in /Users/MY_USER/kubernetes-client/csharp/src/KubernetesClient/generated/Kubernetes.cs:line 12380
   at k8s.KubernetesExtensions.ListNamespacedPodAsync(IKubernetes operations, String namespaceParameter, Nullable`1 allowWatchBookmarks, String continueParameter, String fieldSelector, String labelSelector, Nullable`1 limit, String resourceVersion, String resourceVersionMatch, Nullable`1 timeoutSeconds, Nullable`1 watch, String pretty, CancellationToken cancellationToken) in /Users/MY_USER/kubernetes-client/csharp/src/KubernetesClient/generated/KubernetesExtensions.cs:line 6371
   at k8s.KubernetesExtensions.ListNamespacedPod(IKubernetes operations, String namespaceParameter, Nullable`1 allowWatchBookmarks, String continueParameter, String fieldSelector, String labelSelector, Nullable`1 limit, String resourceVersion, String resourceVersionMatch, Nullable`1 timeoutSeconds, Nullable`1 watch, String pretty) in /Users/MY_USER/kubernetes-client/csharp/src/KubernetesClient/generated/KubernetesExtensions.cs:line 6265
   at simple.PodList.Main(String[] args) in /Users/MY_USER/kubernetes-client/csharp/examples/simple/PodList.cs:line 14
```

**Comment by brendandburns** [comment] 2021-05-19 22:23
Ok, that's the same standard unauthorized that I would expect. So it's at least not throwing any errors. I will also glance at the code to see if I can spot any differences between the two implementations.

**Comment by jarrett-confrey** [comment] 2021-05-20 14:33
i was able to fix the issue with https://github.com/kubernetes-client/csharp/pull/633

**Comment by brendandburns** [comment] 2021-05-24 16:35
Closing this since #633 has merged.

**Closed by brendandburns** 2021-05-24 16:35 UTC

**Comment by amsoedal** [comment] 2021-05-24 16:48
Thanks! When do you think the release including this change will go out?

**Comment by brendandburns** [comment] 2021-05-24 16:55
It's already out:

https://www.nuget.org/packages/KubernetesClient/5.0.9
