### ISSUE TITLE
Certificate validation failure on GKE on 19 version

### ISSUE THREAD

**Issue by CatalinAdlerDF** [kubernetes-client/csharp#585] opened 2021-03-14 10:54 UTC
Hi,

I've upgraded to latest version, 19, and i've started receiving certificate validation failures on listing pods.
Something related to PartialChain trust.

Downgrading to 16 fixed the issue.

I'm on GKE 1.18.12 and on .net 5, if that matters.

I've been looking through the recent commits on master, but i am not seeing anything pertaining; at best the k8s client re-generation on the 18th.

lmk if i can provide more data.

**Comment by tg123** [comment] 2021-03-14 11:19
do you mean `4.0.16`?
starting from `4.0.19`, the sdk is targeting `net5` directly (was `netstandard2.1`)

may i know the detailed error and more info about your server side cert

**Comment by tg123** [comment] 2021-03-15 19:55
could you please try netcore3.x + 4.0.19?
sounds like net5 introduces stricter rules

**Comment by lynxz** [comment] 2021-03-15 20:24
I'm experiencing the same problem however only in ASP.NET core application on net5. Using a console application with net5 or an ASP.NET core application on  netcore3.1 works for me.

**Comment by oekarlsson** [comment] 2021-03-24 15:37
I have the same problem using .net core 5 on an EKS cluster (Kuberentes v1.19). Have only seen it on listing pods...

**Comment by oekarlsson** [comment] 2021-03-24 15:47
Could this be the cause?
https://docs.microsoft.com/en-us/dotnet/core/compatibility/cryptography/5.0/default-cipher-suites-for-tls-on-linux

**Comment by oekarlsson** [comment] 2021-03-24 19:10
Running curl from within a .net core 5 pod in the EKS cluster I cannot reach the API endpoint:
`curl -v https://xxxxxxxxxx.yyy.eu-north-1.eks.amazonaws.com
*   Trying 10.2.171.188:443...
* Connected to xxxxxxxxxx.yyy.eu-north-1.eks.amazonaws.com (10.2.171.188) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Request CERT (13):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate`

So, not a problem with the C# kubernetes client of latest versions but rather .NET 5 in Linux.

**Comment by brendandburns** [comment] 2021-03-25 03:24
I don't think that your curl test is representative. Kubernetes distros generally use their own CAs and thus vanilla curl won't know about the CA.

The real test is to see if `kubectl` works in your container.

**Comment by oekarlsson** [comment] 2021-03-25 08:29
> I don't think that your curl test is representative. Kubernetes distros generally use their own CAs and thus vanilla curl won't know about the CA.
> 
> The real test is to see if `kubectl` works in your container.

You are of course right @brendandburns. curl does not have any knowledge of the ca certificate from the Kubernetes cluster. 

I have now tested kubectl in the container and it works just fine!

After that I added the eks clusters ca certificate to /etc/ssl/certs/ca-certificates.crt 
With the CA Certificate in place curl had no trouble connecting to the Kubernetes API and my app using the C# client version 4.0.20 also started to work (using inclusterconfig to connect)

I really don't know what to do next other than adding the ca certificate to the container on start of my app.

**Comment by CatalinAdlerDF** [comment] 2021-03-25 08:34
Seems to me that, at least the managed k8 services, should have used certificates that have some trusted root in the chain, since the masters are managed by them in the end.

What is curious is what triggered this change in the client? the rules of cert validation did not change out of the sudden, and a untrusted root should not have been working previously as well.

**Comment by tg123** [comment] 2021-03-25 14:06
seems we need to load `/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt` when `InClusterConfig()`

**Comment by tg123** [comment] 2021-03-25 14:07
diff ` /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt` `/etc/ssl/certs/ca-certificates.crt`

**Comment by RemiGaudin** [comment] 2021-03-25 16:24
I have the exact same problem using .NET 5 on an Docker Desktop cluster (Kuberentes v1.19.7). The exception occurs starting from v.19, and downgrading to v.16 is fixing the issue.

**Comment by oekarlsson** [comment] 2021-03-25 17:10
I have run some more tests and printed out what `KubernetesClientConfiguration.InClusterConfig()` found. Host, token and the ca cert are all found (and are correct) and used when I create the Kubernetes Client in code. The host is an IP-nr, but the cert is valid for that IP as an subject alternative name. The error must come later when .NET is trying to make the connection. It seems like the ca cert that exists in the client configuration is not used.

**Comment by tg123** [comment] 2021-03-25 17:16
@oekarlsson could you please set TcpKeepAlive=false and try again 
The different between .16 and .19 is that starting from .19 the sdk is now targeting `net5` instead of `netstandard2.1`

**Comment by oekarlsson** [comment] 2021-03-25 17:28
@tg123 setting TcpKeepAlive=false is the road to success for the moment! It works.

**Comment by tg123** [comment] 2021-03-25 17:30
I will look into why TcpKeepAlive hack makes some different to cert

**Comment by brendandburns** [comment] 2021-03-26 20:36
@tg123 I suspect that the way you are hacking the handler into the http client is the thing causing the problem...

**Comment by jurgyy** [comment] 2021-03-29 07:09
I have the same problem in AKS after I upgraded to Kubernetes client version 4.0.21 from a way older version. And I can confirm that setting the TcpKeepAlive in the `KubernetesClientConfiguration` fixes it for now.

**Comment by ghosh9691** [comment] 2021-03-29 15:07
Facing the same issue with .NET 5.0 and EKS running 1.18. The `TcpKeepAlive = false` hack is a temporary life saver!

**Closed** 2021-04-02 21:52 UTC

**Comment by jefflill** [comment] 2022-06-02 06:33
I just ran into this as well (Jun 2022).  The problem in my case was that I was creating a new `KubernetesClient` along with a new `HttpClient` in the ASP.NET controller, so I be creating a new client for every request.

Creating a single client and using dependency injection fixed the authentication error for me.

**Comment by tg123** [comment] 2022-06-02 11:36
@jefflill may i know your sdk ver?
I remember custom httpclient was banned long time ago.
all inner httpclients are managed by sdk
