### ISSUE TITLE
Octal numbers in Yaml deserialized as decimal numbers

### ISSUE THREAD

**Issue by morfj** [kubernetes-client/csharp#500] opened 2020-10-15 10:07 UTC
`V1ConfigMapVolumeSource -> DefaultMode` requires an integer and its quite common in YAML files that this is written as an octal number (e.g.: 0777). It seems however that the parser is interpreting it as a decimal number. Serializing it back into a YAML string sets the property to `777` which gets rejected by the cluster's validation.

**Comment by brendandburns** [comment] 2020-10-22 16:23
We'll investigate how to do this, I'm not sure how YAML defines hex vs decimal number formats. It may be a bug in the YAML parser...

**Comment by brendandburns** [comment] 2020-10-23 16:38
I reproduced this in a unit test, but I'm not sure why it is happening. It definitely looks like the Yaml parser supports octal numbers, and a simple octal parse -> int works correctly.

I will continue to investigate.

**Comment by brendandburns** [comment] 2020-10-24 15:44
Figured it out. There's a bug in the `YamlDotNet` library.

I sent a fix to them, but I don't know how long it will take to get it merged/released.

**Closed** 2021-02-23 17:21 UTC
Labels: lifecycle/rotten
