### ISSUE TITLE
Cannot Connect to AKS Cluster from Dev Laptop

### ISSUE THREAD

**Issue by nickward13** [kubernetes-client/csharp#175] opened 2018-06-20 03:44 UTC
I'm trying to connect to an RBAC enabled AKS cluster using the recommended code from the README.md, along with a request to list the pods in the default namespace:

var config = KubernetesClientConfiguration.BuildConfigFromConfigFile();
var client = new Kubernetes(config);
client.ListNamespacedPod("default");

The client.ListNamespacedPod command throws an exception "Microsoft.Rest.HttpOperationException: Operation returned an invalid status code 'Forbidden'", with a response content of "pods is forbidden: User \"clusterUser\" cannot list pods in the namespace \"default\"".  Using the same config file via kubectl retrieves a list of pods successfully.

Is this related to the known issue mentioned in the README.md - "Not all auth providers are supported at moment #91", or is it an additional error?  The code appears to connect, but seems to be using a low privelege user account. I couldn't find a suitable issue covering this.  Any suggestions would be great.

**Comment by brendandburns** [comment] 2018-06-25 14:18
@nickward13 what is in your kubeconfig file? is it certificate based auth? Or is it AAD based auth?

I will try to repro.

Thanks!

**Comment by nickward13** [comment] 2018-06-28 05:49
Thanks @brendandburns.  Its certificate based auth - not AAD.

**Comment by brendandburns** [comment] 2018-07-11 04:48
Closing this since we can't seem to reproduce.

**Closed by brendandburns** 2018-07-11 04:48 UTC
