### ISSUE TITLE
ListNamespacedCronJobAsync returns 404 (used to work on older version)

### ISSUE THREAD

**Issue by dannystommen** [kubernetes-client/csharp#820] opened 2022-04-04 06:38 UTC
We're using a pretty outdated version of `KubernetesClient`, (`3.0.16`). When trying to upgrade to version `7.1.9`, listing of cronjobs does not work anymore.

The code
```
var response = await client.ListNamespacedCronJobAsync("my-namespace");
```
And it results in a 404.

When using fiddler, I can see version 3 is making the following api call (stripped out the headers from the response)
```
GET /apis/batch/v1beta1/namespaces/datalake/cronjobs HTTP/1.1

{"kind":"CronJobList","apiVersion":"batch/v1beta1","metadata":{"resourceVersion":"347807292"},"items":[{" ....
```

With version 7, this is the result:
```
GET /apis/batch/v1/namespaces/datalake/cronjobs HTTP/1.1

HTTP/1.1 404 Not Found
Cache-Control: no-cache, private
Content-Type: application/json
Date: Mon, 04 Apr 2022 06:26:24 GMT
Content-Length: 174

{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the server could not find the requested resource","reason":"NotFound","details":{},"code":404}
```

Our K8s cluster is an EKS clusting running on AWS, version 1.20.

Any idea what's causing this?

**Comment by tg123** [comment] 2022-04-04 20:31
could you please update k8s server to 1.21?

7.x is not compatible with 20 and lower

**Comment by dannystommen** [comment] 2022-04-05 06:10
> could you please update k8s server to 1.21?
> 
> 7.x is not compatible with 20 and lower

Ok that's good to know. I'll see if we can get our cluster updated.

**Comment by kibernetik542** [comment] 2022-04-05 08:17
> > could you please update k8s server to 1.21?
> > 7.x is not compatible with 20 and lower
> 
> Ok that's good to know. I'll see if we can get our cluster updated.

I can suggest you quick fix for this and you can handle out if your kube cluster version is greater than or equal to 1.21 you can use current method but otherwise below code will fix you issue:

` var generic = new GenericClient(client, "batch", "v1beta1", "cronjobs");

   var cronjobList = await generic.ListAsync<V1beta1CronJobList>();`

**Comment by brendandburns** [comment] 2022-04-07 16:05
I'm going to close this since this is working as intended.

**Closed by brendandburns** 2022-04-07 16:05 UTC
